Update reverse_engineering.yml
Updated PlantUML to v1.2023.13 and added exception handling for PlantUML.

diff --git a/.github/workflows/reverse_engineering.yml b/.github/workflows/reverse_engineering.yml
--- a/.github/workflows/reverse_engineering.yml
+++ b/.github/workflows/reverse_engineering.yml
@@ -99,8 +99,12 @@ jobs:
         if: ${{ needs.collect_info.outputs.latest_version != env.current_version }}
         run: |
           sudo apt-get install graphviz
-          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.8/plantuml-1.2023.8.jar -O plantuml.jar
-          java -jar plantuml.jar -tsvg to_commit/${{ matrix.directory }}/model_re/uml/*.puml
+          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.13/plantuml-1.2023.13.jar -O plantuml.jar
+          shopt -s nullglob
+          for file in to_commit/matrix_directory/model_re/uml/*.puml; do
+            [ -f "$file" ] || continue
+            java -jar plantuml.jar -tsvg "$file" || echo "Diagram description contains errors: ${file}"
+          done
 
       - name: Update version
         if: ${{ needs.collect_info.outputs.latest_version != env.current_version }}
